// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAObltBjheIx7rhXzCtE3jN_Fbh9bBeYlc',
    appId: '1:783406228817:web:4f8d08097b29a97ae3df70',
    messagingSenderId: '783406228817',
    projectId: 'madact15',
    authDomain: 'madact15.firebaseapp.com',
    storageBucket: 'madact15.firebasestorage.app',
    measurementId: 'G-2ZPNEZTN20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMa5ikxAZmYDfms6UKyuuGjyeMfVPK1Y',
    appId: '1:783406228817:android:a3da48b4cff8e116e3df70',
    messagingSenderId: '783406228817',
    projectId: 'madact15',
    storageBucket: 'madact15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOj9Y7SYR-oPgj7L5j0SRzGwviVwigxQ',
    appId: '1:783406228817:ios:35bc44ada8829483e3df70',
    messagingSenderId: '783406228817',
    projectId: 'madact15',
    storageBucket: 'madact15.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOj9Y7SYR-oPgj7L5j0SRzGwviVwigxQ',
    appId: '1:783406228817:ios:35bc44ada8829483e3df70',
    messagingSenderId: '783406228817',
    projectId: 'madact15',
    storageBucket: 'madact15.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAObltBjheIx7rhXzCtE3jN_Fbh9bBeYlc',
    appId: '1:783406228817:web:f09059ac2a372d15e3df70',
    messagingSenderId: '783406228817',
    projectId: 'madact15',
    authDomain: 'madact15.firebaseapp.com',
    storageBucket: 'madact15.firebasestorage.app',
    measurementId: 'G-VY34T5TMQ1',
  );
}
